name: Tests

on: [ push, pull_request ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Test
      run: |
        mkdir build
        cd build
        cmake ..
        make -j$(nproc) build_and_test
